language: node_js

matrix:
    fast_finish: true
    allow_failures:
        - node_js: "10"
    include:
        - node_js: "8"
        - node_js: "10"

notifications:
    email: false
deploy:
  provider: npm
  skip_cleanup: true
  email:
    secure: ZCdEsxE0k4o214gOY16BMluYInnz+6xxzR7WRqHLSKnfpzFc1LrombhZn2RdwrYjNJogmytNi0OfoWLRak3r/Ftez1N16xbBVpNlF/+Zgpi/X+bjkF+dgV9aw+QK88h3taJlhzRjBzyKAakPIs0fNeZUViLztaUC0QPs3OnbBog=
  api_key:
    secure: JwY3A1WIAfKGe1NxpvWymEOU9cJDCwEkd9G3VeJi7tgyFhzAqZpDY8lo/LFicqGS2CDCYL8S46GhyYLl2rWV0UGE9bWzfesqISG1LgnvMrFn6K2B56+/ER/PNAiqdbDrR0i0ZmeSLVJ0mGhxYxWo1L0eC1pSntIDtNuucwbGbHo=
  on:
    tags: true
    node_js: "8"
